   item {
       id: 1
       name: 'yellow_ball'
   }
   item {

       id: 2
       name: 'yellow_cube'
   }
   item {

       id: 3
       name: 'green_cube'
   }
   item {

       id: 4
       name: 'green_cylinder'
   }
   item {

       id: 5
       name: 'green_hollow_cube'
   }
   item {

       id: 6
       name: 'orange_cross'
   }
   item {

       id: 7
       name: 'orange_star'
   }
   item {

       id: 8
       name: 'red_cylinder'
   }
   item {

       id: 9
       name: 'red_cube'
   }
   item {

       id: 10
       name: 'red_ball'
   }
   item {

       id: 11
       name: 'blue_cube'
   }
   item {

       id: 12
       name: 'blue_triangle'
   }
   item {

       id: 13
       name: 'purple_cross'
   }
   item {

       id: 14
       name: 'purple_star'
   }